Class {
	#name : 'Card',
	#superclass : 'Object',
	#category : 'IngSoft2-Model',
	#package : 'IngSoft2-Model'
}

{ #category : 'testing' }
Card >> isAcceleration [

^false
]

{ #category : 'testing' }
Card >> isCancellation [

^false
]

{ #category : 'testing' }
Card >> isMercenary [

^false
]

{ #category : 'testing' }
Card >> isRedo [

^false
]

{ #category : 'testing' }
Card >> isRepeat [

^false
]

{ #category : 'testing' }
Card >> isSpeed [

^false
]
